// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8m7bmNkoAPSX8he0TJdCBq9jplww6x8',
    appId: '1:173167189912:web:438312a4898b47873b55ed',
    messagingSenderId: '173167189912',
    projectId: 'voila-db8c0',
    authDomain: 'voila-db8c0.firebaseapp.com',
    storageBucket: 'voila-db8c0.firebasestorage.app',
    measurementId: 'G-SJQ81CX9RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJBBYUyNskIN5dxP_WhpLPpzqFoCaFHE',
    appId: '1:173167189912:android:b433abeeeb73cd9b3b55ed',
    messagingSenderId: '173167189912',
    projectId: 'voila-db8c0',
    storageBucket: 'voila-db8c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbegrSeUxW00UYGWR-mJB2K2i8Ts4LFZ4',
    appId: '1:173167189912:ios:f366471db2a043a23b55ed',
    messagingSenderId: '173167189912',
    projectId: 'voila-db8c0',
    storageBucket: 'voila-db8c0.firebasestorage.app',
    iosBundleId: 'com.example.voillas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbegrSeUxW00UYGWR-mJB2K2i8Ts4LFZ4',
    appId: '1:173167189912:ios:f366471db2a043a23b55ed',
    messagingSenderId: '173167189912',
    projectId: 'voila-db8c0',
    storageBucket: 'voila-db8c0.firebasestorage.app',
    iosBundleId: 'com.example.voillas',
  );
}
